flowchart TD
%% generated in 0.03s
    examples__execute["examples.execute<br/>1 funcs"]
    examples__mcp["examples.mcp<br/>1 funcs"]
    examples__resolve["examples.resolve<br/>2 funcs"]
    schemas__codegen["schemas.codegen<br/>20 funcs"]
    src__nlp2uri["src.nlp2uri<br/>377 funcs"]
    schemas__codegen ==>|5| examples__resolve
    src__nlp2uri ==>|5| examples__resolve
    examples__mcp ==>|4| examples__resolve
    examples__execute ==>|4| examples__resolve
    examples__mcp -->|2| src__nlp2uri
    examples__execute -->|2| src__nlp2uri
    examples__resolve -->|1| src__nlp2uri
